# Generated by Django 5.1.4 on 2025-01-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
