version: '3.8'

services:
  web:
    build: .
    container_name: lms_web
    volumes:
      - ./media:/app/media  # Для работы с медиафайлами
    ports:
      - "8000:8000"
    environment:
      DEBUG: '1'
      ALLOWED_HOSTS: '*'
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    container_name: lms_db
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: